version: '2.1'

services:

  librespot:
  
    build: .
    container_name: librespot
    image: librespot-java:latest
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/snd:/dev/snd
