version: '2.1'

services:

  librespot:
    container_name: librespot
    image: agneev/librespot-java
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./user-data:/config
    devices:
      - /dev/snd:/dev/snd
