version: '2.1'

services:

  librespot:
  
    build: 
      context: .
      dockerfile: Dockerfile.source
    container_name: librespot
    image: librespot-java:source
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./user-data:/config
    devices:
      - /dev/snd:/dev/snd
